// view-angular/src/app/features/user/sign-in-page/sign-in-page.component.ts
import { Component } from '@angular/core';
import {
  AjaxRequestService
} from '@app-services/api/ajax-request.service';
import { UserModel } from '@domain/features/user';


@Component({
  selector: 'app-sign-in-page',
  templateUrl: './sign-in-page.component.html',
  styleUrls: ['./sign-in-page.component.scss']
})
export class SignInPageComponent {
  user: UserModel;


  constructor() {
    const ajaxSrv = new AjaxRequestService();
    ajaxSrv.get('assets/dummy-data/user-data.json', {})
    .then((res) => {
      console.log('SignInPageComponent success', res);
      this.user = new UserModel();
      this.user.setData((res as any));
      setTimeout(() => {
        this.user.updateData({ firstname: 'Nathan' });
      }, 2000);
    })
    .catch((err) => {
      console.log('SignInPageComponent error', err);
    });
  }

}

<div>
  User sign in
  <p>
    <span>Firstname: {{ (user?.state$ | async)?.firstname }}</span>
  </p>
</div>

// view-vue/src/app/features/user/sign-in-page/sign-in-page.component.ts
import { Vue, Component, Prop } from 'vue-property-decorator';
import {
  AjaxRequestService,
} from '@app-services/api/ajax-request.service';
import { UserModel } from '@domain/features/user';


@Component({
  name: 'sign-in-page',
})
export default class SignInPageComponent extends Vue {
  public user: UserModel;
  public title!: string;

  constructor() {
    super();

    this.title = 'Hello!';
    this.user = new UserModel();
    this.user.setData({
      firstname: 'Vue',
      lastname: 'Test',
    });

    setTimeout(() => {
      this.user.updateFirstname('Nathan');
    }, 2000);
  }
}
